FROM python:3.7-slim

RUN mkdir /app

COPY requirements.txt /app

RUN pip3 install -r /app/requirements.txt --no-cache-dir

COPY . /app

WORKDIR /app

RUN python manage.py collectstatic --noinput

COPY docker-entrypoint.sh /app

ENTRYPOINT ["sh", "docker-entrypoint.sh"]
